
FROM ubuntu:18.04

########################## DO NO EDIT ABOVE THIS LINE ###############################
#####################################################################################

MAINTAINER Danya Hassan  <dhassan24@kgi.edu>

#####################################################################################
###### Environment settings and dependency installation - DO NO EDIT ################
#####################################################################################

ENV TERM=vt100
ARG DEBIAN_FRONTEND=noninteractive

#Install system dependencies including python, wget, x11, R, etc
RUN apt-get update && \
  apt-get -y --no-install-recommends install apt-utils build-essential dialog gfortran zlib1g-dev libbz2-dev liblzma-dev libpcre3-dev libcurl4-gnutls-dev libssl-dev libxml2-dev xorg-dev wget less openjdk-8-jre-headless python3.7 unzip

#RUN apt-get -y  --no-install-recommends install r-base                                                          ###I blocked this R installation as it was installing an older version
														 ### This older version wouldn't let me install some essential packages, namely tidyverse,		
RUN apt-get -y install texinfo texlive-latex-base texlive-fonts-recommended texlive-fonts-extra
RUN ln -sf /usr/bin/python3.7 /usr/bin/python

#####################################################################################
#################### Take home assignment starts here ###############################
#####################################################################################

#Assignment Details:
#Remember main purposes of a Dockerfile are:
#1.  



#################### Take home assignment ends here #################################
#####################################################################################
######################### DO NO EDIT BELOW THIS LINE ################################

ENV Rscript="Rscript --vanilla"

CMD ["/bin/bash"]
